// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Vt7tOmUnTPD6EDmn_bh7cpDz_X9KvIY',
    appId: '1:1076346718940:web:8a1f852b123858fc688219',
    messagingSenderId: '1076346718940',
    projectId: 'berichtverwaltung',
    authDomain: 'berichtverwaltung.firebaseapp.com',
    storageBucket: 'berichtverwaltung.appspot.com',
    measurementId: 'G-P0JNWCW1W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3fgNFiN__BLpH3NSfn0NUzcjSIX8qsPY',
    appId: '1:1076346718940:android:f42c7ce543369451688219',
    messagingSenderId: '1076346718940',
    projectId: 'berichtverwaltung',
    storageBucket: 'berichtverwaltung.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnWnnAgg42vEHUFNvhclDR-PoPf2uCpU',
    appId: '1:1076346718940:ios:3ae45f59db1a39b2688219',
    messagingSenderId: '1076346718940',
    projectId: 'berichtverwaltung',
    storageBucket: 'berichtverwaltung.appspot.com',
    iosClientId: '1076346718940-9o2nbm9lnbrtus1b8rugmmubatn39cif.apps.googleusercontent.com',
    iosBundleId: 'dev.z4roc.flutter.berichtverwaltungFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLnWnnAgg42vEHUFNvhclDR-PoPf2uCpU',
    appId: '1:1076346718940:ios:3ae45f59db1a39b2688219',
    messagingSenderId: '1076346718940',
    projectId: 'berichtverwaltung',
    storageBucket: 'berichtverwaltung.appspot.com',
    iosClientId: '1076346718940-9o2nbm9lnbrtus1b8rugmmubatn39cif.apps.googleusercontent.com',
    iosBundleId: 'dev.z4roc.flutter.berichtverwaltungFlutter',
  );
}
